### ISSUE TITLE
Etheratom report Error: No coinbase selected!

### ISSUE THREAD

**Issue by plaichat1986** [0mkara/etheratom#104]
I install Ganache,  try the demo in this picture https://user-images.githubusercontent.com/13261372/39013308-a0c2a242-4434-11e8-8122-eb867a7ac624.png.
After I run atom to compile the greeter.sol, the atom notice "No coinbase selected!", Can you tell me where to set the coinbase?

**Comment by 0mkara** [comment]
**First** thing to check if you have demo accounts on ganache.
![screenshot from 2018-05-29 02-16-07](https://user-images.githubusercontent.com/13261372/40629048-6a142cea-62e6-11e8-958b-329c66a6af56.png)

**After that** if Etheratom is set correctly to connect with ganache RPC server then you should be able to see list of ganache accounts like following:
![screenshot from 2018-05-29 02-19-44](https://user-images.githubusercontent.com/13261372/40629113-e4cb6174-62e6-11e8-855b-d2bd79a9246a.png)

Feel free to join [t.me/etheratom](https://t.me/etheratom) for instant help.

**Comment by plaichat1986** [comment]
yes,  just now i change etheratom's setting rpc endpoint from 8545 to 7545, And set Ganache's listen port to 7545, Then the Atom can show ganache accounts list as you show. Thanks
