### ISSUE TITLE
Error: No coinbase selected!

### ISSUE THREAD

**Issue by kenneth** [0mkara/etheratom#106]
how to select?

**Comment by 0mkara** [comment]
Make sure you have correctly pointed etheratom to Geth RPC or ganache RPC.

**Comment by kenneth** [comment]
i have set in settings 
http://127.0.0.1:8545/
ws://127.0.0.1:8546

and start ganache
but why can't select coinable?

**Comment by 0mkara** [comment]
Ganache does not provide a Websocket api. You need to set endpoints correctly. For quick help please join [t.me/etheratom](https://t.me/etheratom)

**Comment by AVert** [comment]
Same error on Geth (((
