### ISSUE TITLE
user name for gitLab

### ISSUE THREAD

**Issue by RockmanR** [0mkara/etheratom#107]
when I execute the command "git clone https://gitlab.com/0mkara/etheratom.git
" to my Mac Terminal, it ask me for gitLab's username and password.I'm a beginner in this field and tried to resolve it by referring to the general issue on other forms but failed to find one. I would appreciate your help.

**Comment by 0mkara** [comment]
It is not gitlab.com. Correct URL is https://github.com/0mkara/etheratom.git.

**Comment by RockmanR** [comment]
Alright, thanks. I guess the installation guide needs to be modified.

**Comment by 0mkara** [comment]
Fixed on update 4.3.2 61c3d3eddd7842d70bbf45609fc53839c2f96ed7
