### ISSUE TITLE
Unable to find openzeppelin contracts

### ISSUE THREAD

**Issue by rajeshsubhankar** [0mkara/etheratom#170]
.sol file contains,
 `import "openzeppelin-solidity/contracts/lifecycle/Pausable.sol";`

Etheratom reports,
`Error: ENOENT: no such file or directory, open '/Users/rajeshsubhankar/Workspace/github/rajeshsubhankar/ProofOfExistance/contracts/openzeppelin-sol'`

openzeppelin contracts are part of `node_modules` folder.

**Comment by 0mkara** [comment]
@rajeshsubhankar  either you specify exact path of `openzeppelin` contracts like `../node_modules/openzeppelin-solidity/contracts/lifecycle/Pausable.sol` or you can import them from github `import 'https://github.com/OpenZeppelin/zeppelin-solidity/contracts/token/ERC721/ERC721Token.sol';`

**Comment by rajeshsubhankar** [comment]
@0mkara Thanks for the feedback but unfortunately this will require a lot of contract code changes. I believe Browserify is taking care of my npm module's path translation. Being new to js world, is this a missing feature in etheratom which will eventually get shipped or more sort of recommendation to use absolute path ?

**Comment by rajeshsubhankar** [comment]
Ohh, its Truffle which helps me in defining import statements in solidity without absolute or relative path for npm packages. [truffle-within-your-contracts](https://truffleframework.com/docs/truffle/getting-started/package-management-via-npm#within-your-contracts)
