### ISSUE TITLE
How to install etheratom

### ISSUE THREAD

**Issue by ZAlliance** [0mkara/etheratom#292]
**Describe the bug**
I am a new user of etheratom , after trying apm install , npm install , install in atom. I still cannot find a way to use it in my ubuntu16.04 ,  is there any guide about the version of atom&dependency？ thanks a lot

**Comment by Soumyanil** [comment]
Please share what problem you are having with installation and the error log.

**Comment by 0mkara** [comment]
To install etheratom use `apm install etheratom`.
If installation is failing please attach error message.
If installation is successful you should be able to activate it with `ctrl+alt+e`.
@ZAlliance

**Comment by Farhadesfandiar** [comment]
I'm using Ubuntu 20.04
apm  2.6.2
npm  6.14.13
node 12.14.1 x64
atom 1.57.0
python 
git 2.25.1

While installing etheratom I face below error:
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/snap/atom/282/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.11.0-43-generic
gyp ERR! command "/snap/atom/282/usr/share/atom/resources/app/apm/bin/node" "/snap/atom/282/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-20211131-244117-1wq94vz.vrzc/node_modules/etheratom/node_modules/scrypt
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-20211131-244117-1wq94vz.vrzc/package.json'
npm WARN react-dom@16.14.0 requires a peer of react@^16.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN remix-tests@0.1.14 requires a peer of yo-yoify@latest but none is installed. You must install peer dependencies yourself.
npm WARN apm-install-dir-20211131-244117-1wq94vz.vrzc No description
npm WARN apm-install-dir-20211131-244117-1wq94vz.vrzc No repository field.
npm WARN apm-install-dir-20211131-244117-1wq94vz.vrzc No README data
npm WARN apm-install-dir-20211131-244117-1wq94vz.vrzc No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by 0mkara** [comment]
@Farhadesfandiar Please use Remix vscode. Etheratom is no longer maintained.
