### ISSUE TITLE
Can't compile big contracts?

### ISSUE THREAD

**Issue by stonecoldpat** [0mkara/etheratom#31]
Hi,

I am able to compile contracts like this: 
https://github.com/amiller/sprites/blob/master/contractSprite.sol

But I cannot seem to compile: 
https://github.com/stonecoldpat/anonymousvoting/blob/master/AnonymousVoting.sol

I am not getting any error messages - I just hit "compile" and nothing happens. 

I actually developed the anonymous voting contract using this atom interface. I've been having trouble ever since upgrading my Mac OS, so I've re-installed everything from scratch... any way I can produce a debug log to find out what is going on?

**Comment by 0mkara** [comment]
Hi,
I tried compiling your AnonymousVoting.sol
I needed to change `pragma solidity 0.4.8;` to `pragma solidity ^0.4.0;` and I commented out `charity = _charity;` on line 539 which was giving `Type uint256 is not implicitly convertible to expected type address.` using Linter package. After that the contract compiled correctly.
I have not yet added error handling. @stonecoldpat
