### ISSUE TITLE
Package not installable:  Authentication failed for 'https://github.com/debris/bignumber.js.git/'

### ISSUE THREAD

**Issue by michaelbaer** [0mkara/etheratom#42]
Hi,
I try to install etheratom using atom package manager and from source. In both cases I get an authentication error for the submodule https://github.com/debris/bignumber.js.git/.
I think 'bignumber.js' is not available anymore?!

> npm ERR! git clone --template=/Users/michael/.atom/.apm/_git-remotes/_templates --mirror https://github.com/debris/bignumber.js.git /Users/michael/.atom/.apm/_git-remotes/git-https-github-com-debris-bignumber-js-git-master-df3f1ce1: Cloning into bare repository '/Users/michael/.atom/.apm/_git-remotes/git-https-github-com-debris-bignumber-js-git-master-df3f1ce1'...
npm ERR! git clone --template=/Users/michael/.atom/.apm/_git-remotes/_templates --mirror https://github.com/debris/bignumber.js.git /Users/michael/.atom/.apm/_git-remotes/git-https-github-com-debris-bignumber-js-git-master-df3f1ce1: remote: Invalid username or password.
npm ERR! git clone --template=/Users/michael/.atom/.apm/_git-remotes/_templates --mirror https://github.com/debris/bignumber.js.git /Users/michael/.atom/.apm/_git-remotes/git-https-github-com-debris-bignumber-js-git-master-df3f1ce1: fatal: Authentication failed for 'https://github.com/debris/bignumber.js.git/'
npm ERR! Darwin 16.6.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/michael/.atom/.apm/.apmrc" "--userconfig" "/Users/michael/.atom/.apmrc" "install" "--runtime=electron" "--target=1.3.15" "--arch=x64"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code 128

> npm ERR! Command failed: git clone --template=/Users/michael/.atom/.apm/_git-remotes/_templates --mirror https://github.com/debris/bignumber.js.git /Users/michael/.atom/.apm/_git-remotes/git-https-github-com-debris-bignumber-js-git-master-df3f1ce1
npm ERR! Cloning into bare repository '/Users/michael/.atom/.apm/_git-remotes/git-https-github-com-debris-bignumber-js-git-master-df3f1ce1'...
npm ERR! remote: Invalid username or password.
npm ERR! fatal: Authentication failed for 'https://github.com/debris/bignumber.js.git/'

**Comment by ddcech** [comment]
It's working for me now.

**Comment by SDeventer** [comment]
Hii, I try to install again but there seems to be another error now.

Installing “etheratom@3.0.1” failed.Hide output…

> scrypt@6.0.3 preinstall /private/var/folders/p4/c1hjy49j139bkfx6_ylz41m00000gn/T/apm-install-dir-117526-79596-1gse7o3.tyma8xgvi/node_modules/.staging/scrypt-1aec2471
> node node-scrypt-preinstall.js


> scrypt@6.0.3 install /private/var/folders/p4/c1hjy49j139bkfx6_ylz41m00000gn/T/apm-install-dir-117526-79596-1gse7o3.tyma8xgvi/node_modules/etheratom/node_modules/scrypt
> node-gyp rebuild

  SOLINK_MODULE(target) Release/copied_files.node
  CC(target) Release/obj.target/scrypt_wrapper/src/util/memlimit.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/pickparams.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/hash.o
  LIBTOOL-STATIC Release/scrypt_wrapper.a
/private/var/folders/p4/c1hjy49j139bkfx6_ylz41m00000gn/T/apm-install-dir-117526-79596-1gse7o3.tyma8xgvi
`-- (empty)


clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
make: *** [Release/scrypt_wrapper.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/p4/c1hjy49j139bkfx6_ylz41m00000gn/T/apm-install-dir-117526-79596-1gse7o3.tyma8xgvi/node_modules/etheratom/node_modules/scrypt
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/p4/c1hjy49j139bkfx6_ylz41m00000gn/T/apm-install-dir-117526-79596-1gse7o3.tyma8xgvi/package.json'
npm WARN apm-install-dir-117526-79596-1gse7o3.tyma8xgvi No description
npm WARN apm-install-dir-117526-79596-1gse7o3.tyma8xgvi No repository field.
npm WARN apm-install-dir-117526-79596-1gse7o3.tyma8xgvi No README data
npm WARN apm-install-dir-117526-79596-1gse7o3.tyma8xgvi No license field.
npm ERR! Darwin 16.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/SvenDeventer/.atom/.apm/.apmrc" "--userconfig" "/Users/SvenDeventer/.atom/.apmrc" "install" "/private/var/folders/p4/c1hjy49j139bkfx6_ylz41m00000gn/T/d-117526-79596-1ocvtqk.qmtjxos9k9/package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the scrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs scrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls scrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/p4/c1hjy49j139bkfx6_ylz41m00000gn/T/apm-install-dir-117526-79596-1gse7o3.tyma8xgvi/npm-debug.log
npm ERR! code 1

**Comment by michaelbaer** [comment]
@0mkara I was able to install the package using the atom-package-manager.
