### ISSUE TITLE
Can't create without password (TestRPC case) 

### ISSUE THREAD

**Issue by ukod** [0mkara/etheratom#47]
I get No password provided a message in the case when I keep password field empty. In case with testrpc password don't need, how I can resolve this problem?

**Comment by 0mkara** [comment]
If you select javascript vm mode no password is needed. If this still does not resolve your issue please add a screenshot of your problem.

**Comment by ukod** [comment]
TestRCP node doesn't need a password. I don't like to use js vm, I need to use exactly TestRPC as connected node
