### ISSUE TITLE
Using Etheratom with Ganache - Unable to Deploy Contract

### ISSUE THREAD

**Issue by polats** [0mkara/etheratom#57]
Hi! I'm trying to use Etheratom with Ganache (http://truffleframework.com/ganache/), but I'm unable to use accounts to deploy contracts. I get an "Account Not Found" when deploying contracts via the Ethereum Interface.

I suspect it's because the password I'm putting into the 'password' fields are wrong (ganache only provides the private keys of the accounts).

The passwords seem to be blank by default (according to https://ethereum.stackexchange.com/questions/11722/where-are-passphrases-stored-in-test-rpc), but I get a 'No password provided' error when I leave the field blank.

Cheers!

**Comment by 0mkara** [comment]
Yeah it does not work with testRPCs yet. Same issue was mentioned #47. I will work on it in near future.

**Comment by haximilian** [comment]
@0mkara What's the current status on this? It's been quite a while since this issue was opened...

**Comment by 0mkara** [comment]
@haximilian I really did not get time to check if it works with ganache or not. After recent updates I can say it works perfectly with backend geth node. If Ganache is supposed to follow Web3 JavaScript API and provides RPC & websocket endpoint then Etheratom should work fine with it.

If you find any error please report it.

**Comment by sierra1bravo** [comment]
Hi
I'm trying to compile and deploy from Etheratom with ganache-cli v6.1.8 (ganache-core: 2.2.1). I'm facing the same problem of the console asking for a password, whereas ganache has no password by default. Any way to make it work?

**Comment by 0mkara** [comment]
Can you please show us some log or screenshots of the error ?

**Comment by sierra1bravo** [comment]
Apologies for reopening an old thread, and thanks very much for the quick response. Here's a screenshot:
https://imgur.com/a/z8BrFC7
I'm now using Ganache (not ganache-cli), and the example is from truffle's MetaCoin box. I still have a password box...what do I enter here?

Also, I'm also getting an error "Error: The data field must be HEX encoded data"...I'm aware that this may not relate to Etheratom at all.




s1b

**Comment by sierra1bravo** [comment]
Thanks @0mkara. I'll try out a newer example and get back if there are any issues.

Meanwhile, thanks very much for your prompt responses.

**Comment by 0mkara** [comment]
Welcome :heart:
