### ISSUE TITLE
Remix creates contract - etheratom does NOT 

### ISSUE THREAD

**Issue by saitam1** [0mkara/etheratom#65]
Here is my contract, which works fine in `Remix`, but `etheratom` doesn't want to create it, after it compiles it.

library.sol:
```
pragma solidity ^0.4.19;

library IntExtended {

    function increment(uint _self) returns (uint) {
        return _self+1;
    }

    function decrement(uint _self) returns (uint) {
        return _self-1;
    }

    function incrementByValue(uint _self, uint _value) returns (uint) {
        return _self + _value;
    }

    function decrementByValue(uint _self, uint _value) returns (uint) {
        return _self - _value;
    }
}
```

testLibrary.sol:
```

pragma solidity ^0.4.19;

import "browser/library.sol";

contract TestLibrary {
    using IntExtended for uint;

    function testIncrement(uint _base) returns (uint) {
        return _base.increment();
    }

    function testDecrement(uint _base) returns (uint) {
        return _base.decrement();
    }

    function testIncrementByValue(uint _base, uint _value) returns (uint) {
        return _base.incrementByValue(_value);
    }

    function testDecrementBaValue(uint _base, uint _value) returns (uint) {
        return _base.decrementByValue(_value);
    }
}

```

**Comment by 0mkara** [comment]
@saitam1 your contract now works. Update Etheratom to latest version. Use web3 provider and `import "./browser/library.sol";`

**Comment by saitam1** [comment]
If I choose `Backend ethereum node` (I have parity running with `Ropsten`), it does not unlock the account (pointed to `127.0.0.1:8180`) and it also doesn't compile the code 

If I choose `Javascript VM` it tells me it can't import a file.

Do I get it right, your add on only work with `geth testnet rpc` so far, all other options are not supported??

**Comment by 0mkara** [comment]
Yes. Only geth testnet is supported/updated for now. Try running geth with `geth --testnet --fast --rpc --rpcapi="eth,web3,personal" --ws --wsorigins="*" --wsapi="eth,web3,personal" console`.
