### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by kiven94** [0mkara/etheratom#83]
Installing “etheratom@4.0.7” failed.Hide output…

> keccak@1.4.0 install C:\Users\kiven\AppData\Local\Temp\apm-install-dir-118223-4308-og034j.dv58tcsor\node_modules\etheratom\node_modules\keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."

> keccak@1.4.0 rebuild C:\Users\kiven\AppData\Local\Temp\apm-install-dir-118223-4308-og034j.dv58tcsor\node_modules\etheratom\node_modules\keccak
> node-gyp rebuild

C:\Users\kiven\AppData\Local\Temp\apm-install-dir-118223-4308-og034j.dv58tcsor\node_modules\etheratom\node_modules\keccak>if not defined npm_config_node_gyp (node "C:\Users\kiven\AppData\Local\atom\app-1.25.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\kiven\AppData\Local\atom\app-1.25.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
�ڴ˽���������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
MSBUILD : error MSB3428: δ�ܼ��� Visual C++ ������VCBuild.exe����Ҫ���������⣬1) ��װ .NET Framework 2.0 SDK��2) ��װ Microsoft Visual Studio 2005���� 3) ��������������װ��������λ�ã��뽫��λ�����ӵ�ϵͳ·���С� [C:\Users\kiven\AppData\Local\Temp\apm-install-dir-118223-4308-og034j.dv58tcsor\node_modules\etheratom\node_modules\keccak\build\binding.sln]
"Keccak bindings compilation fail. Pure JS implementation will be used."

> secp256k1@3.5.0 install C:\Users\kiven\AppData\Local\Temp\apm-install-dir-118223-4308-og034j.dv58tcsor\node_modules\etheratom\node_modules\secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."

> secp256k1@3.5.0 rebuild C:\Users\kiven\AppData\Local\Temp\apm-install-dir-118223-4308-og034j.dv58tcsor\node_modules\etheratom\node_modules\secp256k1
> node-gyp rebuild

C:\Users\kiven\AppData\Local\Temp\apm-install-dir-118223-4308-og034j.dv58tcsor\node_modules\etheratom\node_modules\secp256k1>if not defined npm_config_node_gyp (node "C:\Users\kiven\AppData\Local\atom\app-1.25.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\kiven\AppData\Local\atom\app-1.25.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
�ڴ˽���������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
MSBUILD : error MSB3428: δ�ܼ��� Visual C++ ������VCBuild.exe����Ҫ���������⣬1) ��װ .NET Framework 2.0 SDK��2) ��װ Microsoft Visual Studio 2005���� 3) ��������������װ��������λ�ã��뽫��λ�����ӵ�ϵͳ·���С� [C:\Users\kiven\AppData\Local\Temp\apm-install-dir-118223-4308-og034j.dv58tcsor\node_modules\etheratom\node_modules\secp256k1\build\binding.sln]
"Secp256k1 bindings compilation fail. Pure JS implementation will be used."

> sha3@1.2.0 install C:\Users\kiven\AppData\Local\Temp\apm-install-dir-118223-4308-og034j.dv58tcsor\node_modules\etheratom\node_modules\sha3
> node-gyp rebuild

C:\Users\kiven\AppData\Local\Temp\apm-install-dir-118223-4308-og034j.dv58tcsor\node_modules\etheratom\node_modules\sha3>if not defined npm_config_node_gyp (node "C:\Users\kiven\AppData\Local\atom\app-1.25.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\kiven\AppData\Local\atom\app-1.25.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
�ڴ˽���������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
MSBUILD : error MSB3428: δ�ܼ��� Visual C++ ������VCBuild.exe����Ҫ���������⣬1) ��װ .NET Framework 2.0 SDK��2) ��װ Microsoft Visual Studio 2005���� 3) ��������������װ��������λ�ã��뽫��λ�����ӵ�ϵͳ·���С� [C:\Users\kiven\AppData\Local\Temp\apm-install-dir-118223-4308-og034j.dv58tcsor\node_modules\etheratom\node_modules\sha3\build\binding.sln]
C:\Users\kiven\AppData\Local\Temp\apm-install-dir-118223-4308-og034j.dv58tcsor
`-- (empty)

gyp ERR! build error 
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\kiven\AppData\Local\atom\app-1.25.0\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\kiven\\AppData\\Local\\atom\\app-1.25.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\kiven\\AppData\\Local\\atom\\app-1.25.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\kiven\AppData\Local\Temp\apm-install-dir-118223-4308-og034j.dv58tcsor\node_modules\etheratom\node_modules\keccak
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\kiven\\AppData\\Local\\atom\\app-1.25.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\kiven\\AppData\\Local\\atom\\app-1.25.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "run" "rebuild"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keccak@1.4.0 rebuild script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the keccak package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs keccak
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls keccak
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\kiven\AppData\Local\Temp\apm-install-dir-118223-4308-og034j.dv58tcsor\node_modules\etheratom\node_modules\keccak\npm-debug.log
gyp ERR! build error 
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\kiven\AppData\Local\atom\app-1.25.0\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\kiven\\AppData\\Local\\atom\\app-1.25.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\kiven\\AppData\\Local\\atom\\app-1.25.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\kiven\AppData\Local\Temp\apm-install-dir-118223-4308-og034j.dv58tcsor\node_modules\etheratom\node_modules\secp256k1
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\kiven\\AppData\\Local\\atom\\app-1.25.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\kiven\\AppData\\Local\\atom\\app-1.25.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "run" "rebuild"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! secp256k1@3.5.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the secp256k1@3.5.0 rebuild script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs secp256k1
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\kiven\AppData\Local\Temp\apm-install-dir-118223-4308-og034j.dv58tcsor\node_modules\etheratom\node_modules\secp256k1\npm-debug.log
gyp ERR! build error 
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\kiven\AppData\Local\atom\app-1.25.0\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\kiven\\AppData\\Local\\atom\\app-1.25.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\kiven\\AppData\\Local\\atom\\app-1.25.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\kiven\AppData\Local\Temp\apm-install-dir-118223-4308-og034j.dv58tcsor\node_modules\etheratom\node_modules\sha3
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\kiven\AppData\Local\Temp\apm-install-dir-118223-4308-og034j.dv58tcsor\package.json'
npm WARN apm-install-dir-118223-4308-og034j.dv58tcsor No description
npm WARN apm-install-dir-118223-4308-og034j.dv58tcsor No repository field.
npm WARN apm-install-dir-118223-4308-og034j.dv58tcsor No README data
npm WARN apm-install-dir-118223-4308-og034j.dv58tcsor No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\kiven\\AppData\\Local\\atom\\app-1.25.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\kiven\\AppData\\Local\\atom\\app-1.25.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\kiven\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\kiven\\.atom\\.apmrc" "install" "C:\\Users\\kiven\\AppData\\Local\\Temp\\d-118223-4308-b0zetf.2a4z9i19k9\\package.tgz" "--runtime=electron" "--target=1.7.11" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! sha3@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sha3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sha3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sha3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\kiven\AppData\Local\Temp\apm-install-dir-118223-4308-og034j.dv58tcsor\npm-debug.log
npm ERR! code 1

I've installed the python 2.7 and also try to install from the Atom packages but still failed.

**Comment by 0mkara** [comment]
same as #55 
Please, use the package "windows-build-tools". Related with Visual C++ vs. Python.
https://github.com/felixrieseberg/windows-build-tools
