### ISSUE TITLE
Install on Ubuntu 17.10 fails

### ISSUE THREAD

**Issue by mysim1** [0mkara/etheratom#88]
keccak@1.4.0 install /tmp/apm-install-dir-118321-1655-xbwr19.idaw8tcsor/node_modules/etheratom/node_modules/keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."

> keccak@1.4.0 rebuild /tmp/apm-install-dir-118321-1655-xbwr19.idaw8tcsor/node_modules/etheratom/node_modules/keccak
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-118321-1655-xbwr19.idaw8tcsor/node_modules/etheratom/node_modules/keccak/build'
  CXX(target) Release/obj.target/keccak/src/addon.o
keccak.target.mk:112: recipe for target 'Release/obj.target/keccak/src/addon.o' failed
make: Leaving directory '/tmp/apm-install-dir-118321-1655-xbwr19.idaw8tcsor/node_modules/etheratom/node_modules/keccak/build'
Keccak bindings compilation fail. Pure JS implementation will be used.

> secp256k1@3.5.0 install /tmp/apm-install-dir-118321-1655-xbwr19.idaw8tcsor/node_modules/etheratom/node_modules/secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."

> secp256k1@3.5.0 rebuild /tmp/apm-install-dir-118321-1655-xbwr19.idaw8tcsor/node_modules/etheratom/node_modules/secp256k1
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-118321-1655-xbwr19.idaw8tcsor/node_modules/etheratom/node_modules/secp256k1/build'
  CXX(target) Release/obj.target/secp256k1/src/addon.o
secp256k1.target.mk:142: recipe for target 'Release/obj.target/secp256k1/src/addon.o' failed
make: Leaving directory '/tmp/apm-install-dir-118321-1655-xbwr19.idaw8tcsor/node_modules/etheratom/node_modules/secp256k1/build'
Secp256k1 bindings compilation fail. Pure JS implementation will be used.

> sha3@1.2.0 install /tmp/apm-install-dir-118321-1655-xbwr19.idaw8tcsor/node_modules/etheratom/node_modules/sha3
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-118321-1655-xbwr19.idaw8tcsor/node_modules/etheratom/node_modules/sha3/build'
  CXX(target) Release/obj.target/sha3/src/addon.o
sha3.target.mk:98: recipe for target 'Release/obj.target/sha3/src/addon.o' failed
make: Leaving directory '/tmp/apm-install-dir-118321-1655-xbwr19.idaw8tcsor/node_modules/etheratom/node_modules/sha3/build'
/tmp/apm-install-dir-118321-1655-xbwr19.idaw8tcsor
└── (empty)

make: g++: Command not found
make: *** [Release/obj.target/keccak/src/addon.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.13.0-36-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-118321-1655-xbwr19.idaw8tcsor/node_modules/etheratom/node_modules/keccak
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Linux 4.13.0-36-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/npm" "run" "rebuild"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keccak@1.4.0 rebuild script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the keccak package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs keccak
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls keccak
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-118321-1655-xbwr19.idaw8tcsor/node_modules/etheratom/node_modules/keccak/npm-debug.log
make: g++: Command not found
make: *** [Release/obj.target/secp256k1/src/addon.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.13.0-36-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-118321-1655-xbwr19.idaw8tcsor/node_modules/etheratom/node_modules/secp256k1
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Linux 4.13.0-36-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/npm" "run" "rebuild"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! secp256k1@3.5.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the secp256k1@3.5.0 rebuild script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs secp256k1
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-118321-1655-xbwr19.idaw8tcsor/node_modules/etheratom/node_modules/secp256k1/npm-debug.log
make: g++: Command not found
make: *** [Release/obj.target/sha3/src/addon.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.13.0-36-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-118321-1655-xbwr19.idaw8tcsor/node_modules/etheratom/node_modules/sha3
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-118321-1655-xbwr19.idaw8tcsor/package.json'
npm WARN apm-install-dir-118321-1655-xbwr19.idaw8tcsor No description
npm WARN apm-install-dir-118321-1655-xbwr19.idaw8tcsor No repository field.
npm WARN apm-install-dir-118321-1655-xbwr19.idaw8tcsor No README data
npm WARN apm-install-dir-118321-1655-xbwr19.idaw8tcsor No license field.
npm ERR! Linux 4.13.0-36-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/hans/.atom/.apm/.apmrc" "--userconfig" "/home/hans/.atom/.apmrc" "install" "/tmp/d-118321-1655-10cnh1r.mbvm927qfr/package.tgz" "--runtime=electron" "--target=1.6.16" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! sha3@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sha3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sha3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sha3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-118321-1655-xbwr19.idaw8tcsor/npm-debug.log
npm ERR! code 1

**Comment by 0mkara** [comment]
`make: g++: Command not found` do you have `build-essential` installed ?

**Comment by mysim1** [comment]
Hi Omkara, Yes I do. See:
**build-essential** is already the newest version (12.4ubuntu1).

**Comment by 0mkara** [comment]
**keaccak** & **secp256k1** issues are related to #36 . Following is the summarized things you would like to check to resolve this issue.

- [ ] python 2 installed & `path` is set properly
- [ ] **build-essentials** are installed
- [ ] try `node-gyp rebuild`
- [ ] start atom with cd `atom .`
- [ ] node & node-gyp is updated

Let me know @mysim1 if you still have those errors.

**Comment by mysim1** [comment]
I did. I managed to remove the problems with **keccak** and **secp256k1**. The node-gyp rebuild command for **sha3** still fails. Links found inside #36 that tackle the truffle installation, solutions dont work.

**Comment by 0mkara** [comment]
What is the latest error you get after resolving **keccak** and **secp256k1** issue ?

**Comment by mysim1** [comment]
So. about those build-essentials. Not sure why. But the g++ command wasn't resolvable using '''which g++''' Because I noticed there was an error '''make: g++ command was not found'''. I basically did:
sudo apt-get autoremove g++ 
then 
apt-get install build-essential g++
Now it resolved the g++ command and the sha3 module succesfully rebuild.
Now: installing etheratom through IDE, CLI works.

Thanks for supporting this effort.
