### ISSUE TITLE
Unable to select Javascript VM

### ISSUE THREAD

**Issue by B0rner** [0mkara/etheratom#89]
Hey,

I like to use Etheratom in an "offline" environment to create contracts an deploy them locally in an Javascript VM.
(Don't like to deploy every single test in the blockchain)
Instaling Etheratom was without problems, but if I enable the Etheratom panel (ctrl+alt+v), the "Javascript VM"  radio button is not shown.
I'm only able to connect to my local running geth node.
But this ist not what I'm looking for.

So how can I switch/enable to Javascript VM?

(Running  atom 1.26 with etheratom 4.2.1 on current linx mint)

Thank you.

**Comment by 0mkara** [comment]
Use [Ganache](http://truffleframework.com/ganache/)

**Comment by B0rner** [comment]
Is Ganache the way to enable the Javascript VM or should I use this as an alternative local running blockchain for tests?

**Comment by 0mkara** [comment]
Ganache is currently most appropriate application to run Javascript VM. You should use it to test your contracts. @B0rner
