### ISSUE TITLE
Atom Package dependency necessity

### ISSUE THREAD

**Issue by mysim1** [0mkara/etheratom#90]
I am actually installing:
```https://atom.io/packages/language-ethereum```
etheratom depends on:
```https://atom.io/packages/language-solidity```
questions:
* Co-existence a problem?
* do I really need language-solidity if I have language-ethereum?

**Comment by 0mkara** [comment]
No those are optional package-deps and there should not be any problem if they co-exists or if you opt not to use any of them.

**Comment by mysim1** [comment]
Thnx!
